'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),child=require('node:child_process');
const {transform}=require('./build-prototype-blades.cjs'),{inspectArchive}=require('./inspect-archive.cjs');
const root=__dirname;
function asar(entries,tail=''){const h={files:{}},data=[];let offset=0;for(const [name,source] of Object.entries(entries)){const bytes=Buffer.isBuffer(source)?source:Buffer.from(source),parts=name.split('/');let parent=h;for(const part of parts.slice(0,-1))parent=parent.files[part]??={files:{}};parent.files[parts.at(-1)]={size:bytes.length,offset:String(offset)};data.push(bytes);offset+=bytes.length;}const json=Buffer.from(JSON.stringify(h)),aligned=Math.ceil(json.length/4)*4,prefix=Buffer.alloc(16+aligned);prefix.writeUInt32LE(4,0);prefix.writeUInt32LE(8+aligned,4);prefix.writeUInt32LE(4+aligned,8);prefix.writeUInt32LE(json.length,12);json.copy(prefix,16);return Buffer.concat([prefix,...data,Buffer.from(tail)]);}
function clean(){return {
 'node_modules/rz-usb-detect/index.js':'args = args.concat(function(err, devices) {}); detection.registerAdded(function(device) {}); detection.registerRemoved(function(device) {});',
 'node_modules/node-rz-hid/nodehid.js':'function HID() {} function enumerate(){return binding.devices.apply(HID,arguments);}',
 'electron/main.js':'ipc.handle("ffiPreload",(event,a,b)=>nativeAlias.callDLL(event,a,b));ipc.handle("ffiPreloadAsync",async(event,a,b)=>nativeAlias.callDLLAsync(event,a,b));ipc.handle("ffiSubPreloadAsync",async(event,a,b)=>otherAlias.callDLLAsync(event,a,b));ipc.handle("mappingEngineAction",async(event,a)=>mappingAlias.callDLL(event,a));ipc.handle("simpleServiceAction",async(event,a)=>{});ipc.handle("lightingDriver",async(event,a)=>{});ipc.handle("electronAction",async(event,request)=>{switch(request.action){case"GetServiceStatus":return statusAlias(service,request);case"StartService":return startAlias(service,request);case"StopService":return stopAlias(service,request);}return systemAlias.callDLL(event,request);});',
 'electron/modules/mapping_engine/win/index.js':'if(device){engine?.ffiMappingEngine?.eventEmitter.emit("device",device);}'
};}
function write(t,bytes){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'blocker-inspect-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'app.asar');fs.writeFileSync(file,bytes);return file;}
test('classifies a current deterministic transform from active ASAR entries',t=>{const file=write(t,transform(asar(clean())).result),r=inspectArchive(file);assert.equal(r.State,'CurrentPatch');assert.match(r.ArchiveSha256,/^[a-f0-9]{64}$/);assert.equal(r.Evidence.length,2);});
test('classifies known legacy helper bytes and call-site profile',t=>{const entries=clean(),generated=transform(asar(entries)).changed;entries['openblade-device-exclusion.cjs']=fs.readFileSync(path.join(root,'device-exclusion-universal.cjs'));entries['openblade-native-exclusion.cjs']=fs.readFileSync(path.join(root,'native-exclusion-universal.cjs'));entries['blade-device-registry.json']=fs.readFileSync(path.join(root,'blade-device-registry.json'));for(const name of ['node_modules/rz-usb-detect/index.js','node_modules/node-rz-hid/nodehid.js','electron/modules/mapping_engine/win/index.js'])entries[name]=generated.get(name);let main=generated.get('electron/main.js').toString();for(const [action,callee] of [['GetServiceStatus','statusAlias'],['StartService','startAlias'],['StopService','stopAlias']])main=main.replace('case"'+action+'":return obNativeExclusion.assertAllowed("electronAction",event,request),'+callee+'(service,request);','case"'+action+'":return '+callee+'(service,request);');entries['electron/main.js']=main;assert.equal(inspectArchive(write(t,asar(entries))).State,'LegacyPatch');});
test('recognized incomplete or unfamiliar edits are partial',t=>{const entries=clean();entries['openblade-device-exclusion.cjs']='unknown helper OPENBLADE_DEVICE_EXCLUDED';assert.equal(inspectArchive(write(t,asar(entries))).State,'PartialPatch');const built=transform(asar(clean())).result,headerLength=built.readUInt32LE(12),base=8+built.readUInt32LE(4),header=JSON.parse(built.subarray(16,16+headerLength));let entry=header.files.electron.files['main.js'];const main=built.subarray(base+Number(entry.offset),base+Number(entry.offset)+entry.size).toString().replace('obNativeExclusion.assertAllowed("lightingDriver",event,a);','void 0;/* obNativeExclusion.assertAllowed("lightingDriver",event,a); */');assert.match(main,/\/\* obNativeExclusion\.assertAllowed\("lightingDriver"/);const changed=clean();changed['openblade-device-exclusion.cjs']=fs.readFileSync(path.join(root,'device-exclusion-universal.cjs'));changed['openblade-native-exclusion.cjs']=fs.readFileSync(path.join(root,'native-exclusion-universal.cjs'));changed['blade-device-registry.json']=Buffer.from(JSON.stringify(JSON.parse(fs.readFileSync(path.join(root,'blade-device-registry.json'))),null,2)+'\n');for(const name of ['node_modules/rz-usb-detect/index.js','node_modules/node-rz-hid/nodehid.js','electron/modules/mapping_engine/win/index.js']){let node=header;for(const part of name.split('/'))node=node.files[part];changed[name]=built.subarray(base+Number(node.offset),base+Number(node.offset)+node.size);}changed['electron/main.js']=main;assert.equal(inspectArchive(write(t,asar(changed))).State,'PartialPatch');});
test('no trace result requires core entries and ignores unreferenced stale payload',t=>{assert.equal(inspectArchive(write(t,asar(clean(),'openblade-device-exclusion.cjs obNativeExclusion.assertAllowed'))).State,'NoPatchDetected');const missing=clean();delete missing['electron/main.js'];assert.equal(inspectArchive(write(t,asar(missing))).State,'Unreadable');});
test('malformed bounds are unreadable and CLI emits the documented JSON shape',t=>{const bad=Buffer.alloc(16);bad.writeUInt32LE(4,0);bad.writeUInt32LE(0xffffffff,12);const badFile=write(t,bad),badResult=inspectArchive(badFile);assert.equal(badResult.State,'Unreadable');assert.match(badResult.ArchiveSha256,/^[a-f0-9]{64}$/);const cleanFile=write(t,asar(clean())),run=child.spawnSync(process.execPath,[path.join(__dirname,'inspect-archive.cjs'),cleanFile],{encoding:'utf8'});assert.equal(run.status,0);assert.deepEqual(Object.keys(JSON.parse(run.stdout)),['State','ArchiveSha256','Evidence']);});
