'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{transform,prepare}=require('./build-prototype-blades.cjs');
function asar(entries){const h={files:{}},data=[];let offset=0;for(const [name,source] of Object.entries(entries)){const bytes=Buffer.from(source),parts=name.split('/');let parent=h;for(const p of parts.slice(0,-1))parent=parent.files[p]??={files:{}};parent.files[parts.at(-1)]={size:bytes.length,offset:String(offset)};data.push(bytes);offset+=bytes.length;}const json=Buffer.from(JSON.stringify(h)),aligned=Math.ceil(json.length/4)*4,p=Buffer.alloc(16+aligned);p.writeUInt32LE(4,0);p.writeUInt32LE(8+aligned,4);p.writeUInt32LE(4+aligned,8);p.writeUInt32LE(json.length,12);json.copy(p,16);return Buffer.concat([p,...data]);}
function fixture(){return {
 'package.json':'{"version":"99.100.12345"}',
 'untouched.txt':'a different future build',
 'node_modules/rz-usb-detect/index.js':'args = args.concat(function(err, devices) {}); detection.registerAdded(function(device) {}); detection.registerRemoved(function(device) {});',
 'node_modules/node-rz-hid/nodehid.js':'function HID() {} function enumerate(){return binding.devices.apply(HID,arguments);}',
 'electron/main.js':'ipc.handle("ffiPreload",(event,a,b)=>nativeAlias.callDLL(event,a,b));ipc.handle("ffiPreloadAsync",async(event,a,b)=>nativeAlias.callDLLAsync(event,a,b));ipc.handle("ffiSubPreloadAsync",async(event,a,b)=>otherAlias.callDLLAsync(event,a,b));ipc.handle("mappingEngineAction",async(event,a)=>mappingAlias.callDLL(event,a));ipc.handle("simpleServiceAction",async(event,a)=>{});ipc.handle("lightingDriver",async(event,a)=>{});ipc.handle("electronAction",async(event,request)=>{switch(request.action){case"GetServiceStatus":return statusAlias(service,request);case"StartService":return startAlias(service,request);case"StopService":return stopAlias(service,request);}return systemAlias.callDLL(event,request);});',
 'electron/modules/mapping_engine/win/index.js':'if(device){engine?.ffiMappingEngine?.eventEmitter.emit("device",device);}'
};}
test('future version and renamed native/service aliases transform without hash allowlist',()=>{const result=transform(asar(fixture()));assert.equal(result.report.changes.length,7);assert.equal(result.report.untouchedPackedFilesVerified,2);assert.match(result.changed.get('electron/main.js').toString(),/assertAllowed\("electronAction",event,request\),startAlias/);assert.equal(result.report.bladeProductIds.length,40);});
test('each missing mandatory native route stops the entire transformation',()=>{for(const route of ['ffiPreload','ffiPreloadAsync','ffiSubPreloadAsync','mappingEngineAction','simpleServiceAction','lightingDriver','electronAction','GetServiceStatus','StartService','StopService']){const f=fixture();f['electron/main.js']=f['electron/main.js'].replace('"'+route+'"','"changedRoute"');assert.throws(()=>transform(asar(f)),/missing or ambiguous/);}});
test('duplicate anchor and already-patched source are refused',()=>{const f=fixture();f['electron/main.js']+=f['electron/main.js'];assert.throws(()=>transform(asar(f)),/missing or ambiguous/);assert.throws(()=>transform(transform(asar(fixture())).result),/Already patched/);});
test('missing wrapper, changed mapping and malformed archive fail closed',()=>{const f=fixture();delete f['node_modules/node-rz-hid/nodehid.js'];assert.throws(()=>transform(asar(f)),/Unsupported input/);const m=fixture();m['electron/modules/mapping_engine/win/index.js']='otherLayout();';assert.throws(()=>transform(asar(m)),/missing or ambiguous/);assert.throws(()=>transform(Buffer.from('bad')),/Invalid ASAR/);});
test('preparation records actual new executable and source hashes without replacing prior output',t=>{const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'blocker-build-'));t.after(()=>fs.rmSync(scratch,{recursive:true,force:true}));const source=path.join(scratch,'original.asar'),exe=path.join(scratch,'RazerAppEngine.exe'),out=path.join(scratch,'one');fs.writeFileSync(source,asar(fixture()));fs.writeFileSync(exe,'future executable fixture');const m=prepare(source,exe,out);assert.match(m.executableSha256,/^[a-f0-9]{64}$/);assert(fs.readFileSync(source).equals(fs.readFileSync(path.join(out,'original.asar'))));assert.throws(()=>prepare(source,exe,out),/already exists/);fs.writeFileSync(exe,'another future executable');const second=prepare(source,exe,path.join(scratch,'two'));assert.notEqual(second.executableSha256,m.executableSha256);const broken=fixture();broken['electron/main.js']='changed layout';fs.writeFileSync(source,asar(broken));assert.throws(()=>prepare(source,exe,path.join(scratch,'invalid')),/missing or ambiguous/);assert(!fs.existsSync(path.join(scratch,'invalid')));assert(fs.existsSync(path.join(out,'original.asar')));});

test('failed structural preparation produces a sanitized issue report and no patch output',t=>{const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'blocker-incompatible-'));t.after(()=>fs.rmSync(scratch,{recursive:true,force:true}));const source=path.join(scratch,'private-serial-source.asar'),exe=path.join(scratch,'RazerAppEngine.exe'),output=path.join(scratch,'output'),f=fixture();f['electron/main.js']=f['electron/main.js'].replace('"ffiPreload"','"changedRoute"');fs.writeFileSync(source,asar(f));fs.writeFileSync(exe,'inert executable');const before=fs.readFileSync(source);let failure;try{prepare(source,exe,output);}catch(error){failure=error;}assert(failure);const old=console.error;console.error=()=>{};let text;try{text=require('./failure-report.cjs').report({stage:'Build',error:failure,archive:source,executable:exe},path.join(scratch,'diagnostics'));}finally{console.error=old;}assert.match(text,/Anchor: ffiPreload/);assert.match(text,/Anchor matches: 0/);assert(!text.includes(scratch));assert(!text.includes('private-serial'));assert(!fs.existsSync(output));assert(fs.readFileSync(source).equals(before));assert.equal(fs.readdirSync(path.join(scratch,'diagnostics')).length,1);});
